# Generated by Django 4.2.7 on 2024-01-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemanagementbookinglistusersetting',
            name='api',
            field=models.CharField(default='storagemanagementAPI:booking_list', help_text='Url Adresse der API', max_length=200, verbose_name='API Url'),
        ),
        migrations.AlterField(
            model_name='storagemanagementbookingoverviewusersetting',
            name='api',
            field=models.CharField(default='storagemanagementAPI:booking_list', help_text='Url Adresse der API', max_length=200, verbose_name='API Url'),
        ),
        migrations.AlterField(
            model_name='storagemanagementbookingtableusersetting',
            name='api',
            field=models.CharField(default='storagemanagementAPI:booking_list', help_text='Url Adresse der API', max_length=200, verbose_name='API Url'),
        ),
    ]
