# Generated by Django 4.2.2 on 2023-11-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerdata',
            options={'default_permissions': (), 'ordering': [], 'permissions': (('add_offerdata', 'OfferData can view create'), ('authorize_true_offerdata', 'OfferData can authorize true'), ('authorize_false_offerdata', 'OfferData can authorize false'), ('change_offerdata', 'OfferData can view change'), ('delete_offerdata', 'OfferData can view delete'), ('detail_offerdata', 'OfferData can view detail'), ('list_offerdata', 'OfferData can view list'), ('send_offerdata', 'OfferData can send offerdata'), ('table_offerdata', 'OfferData can view table'), ('view_offerdata', 'OfferData can view overview')), 'verbose_name': 'Angebot Artikel', 'verbose_name_plural': 'Angebote Artikel'},
        ),
        migrations.AlterField(
            model_name='offerdatabasemodel',
            name='done',
            field=models.BooleanField(blank=True, default=False, help_text='Angebot wurde erledigt.', verbose_name='Erledigt'),
        ),
        migrations.AlterField(
            model_name='offerdatabasemodel',
            name='recived',
            field=models.BooleanField(blank=True, default=False, help_text='Bestellung angekommen.', verbose_name='Erhalten.'),
        ),
        migrations.AlterField(
            model_name='offerdatabasemodel',
            name='sent',
            field=models.BooleanField(blank=True, default=False, help_text='Bestellung wurde rausgeschickt.', verbose_name='Bestellt.'),
        ),
        migrations.AlterField(
            model_name='orderdatabasemodel',
            name='done',
            field=models.BooleanField(blank=True, default=False, help_text='Angebot wurde erledigt.', verbose_name='Erledigt'),
        ),
        migrations.AlterField(
            model_name='orderdatabasemodel',
            name='recived',
            field=models.BooleanField(blank=True, default=False, help_text='Bestellung angekommen.', verbose_name='Erhalten.'),
        ),
        migrations.AlterField(
            model_name='orderdatabasemodel',
            name='sent',
            field=models.BooleanField(blank=True, default=False, help_text='Bestellung wurde rausgeschickt.', verbose_name='Bestellt.'),
        ),
    ]
