# Generated by Django 4.2.7 on 2024-01-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0002_alter_storagemanagementbookinglistusersetting_api_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemanagementstoragelistusersetting',
            name='supplieritem_name',
            field=models.BooleanField(default=True, help_text='Darstellung des Lagerartikel', verbose_name='Artikel'),
        ),
        migrations.AlterField(
            model_name='storagemanagementstoragelistusersetting',
            name='supplieritem_reference_number',
            field=models.BooleanField(default=True, help_text='Darstellung der Artikel Referenz', verbose_name='Artikel Referenz'),
        ),
        migrations.AlterField(
            model_name='storagemanagementstoragetableusersetting',
            name='supplieritem_name',
            field=models.BooleanField(default=True, help_text='Darstellung des Artikel', verbose_name='Artikel'),
        ),
        migrations.AlterField(
            model_name='storagemanagementstoragetableusersetting',
            name='supplieritem_reference_number',
            field=models.BooleanField(default=True, help_text='Darstellung der Artikel Referenz', verbose_name='Artikel Referenz'),
        ),
    ]
