# Generated by Django 4.2.2 on 2023-11-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0002_alter_offerdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdata',
            options={'default_permissions': (), 'ordering': [], 'permissions': (('add_orderdata', 'OrderData can view create'), ('authorize_true_orderdata', 'OrderData can authorize true'), ('authorize_false_orderdata', 'OrderData can authorize false'), ('change_orderdata', 'OrderData can view change'), ('delete_orderdata', 'OrderData can view delete'), ('detail_orderdata', 'OrderData can view detail'), ('list_orderdata', 'OrderData can view list'), ('table_orderdata', 'OrderData can view table'), ('view_orderdata', 'OrderData can view overview')), 'verbose_name': 'Bestellung Artikel', 'verbose_name_plural': 'Bestellungen Artikel'},
        ),
        migrations.AddField(
            model_name='offerbasemodel',
            name='offer_file',
            field=models.FileField(blank=True, help_text='Erhaltenes Angebot', null=True, upload_to='storagemanagement/offer/', verbose_name='Angebot'),
        ),
        migrations.AddField(
            model_name='orderbasemodel',
            name='confirmation',
            field=models.FileField(blank=True, help_text='Erhaltene Auftragsbestätigung', null=True, upload_to='storagemanagement/offer/confirmation/', verbose_name='Auftragsbestätigung'),
        ),
        migrations.AddField(
            model_name='orderbasemodel',
            name='delivery_note',
            field=models.FileField(blank=True, help_text='Erhaltener Lieferschein', null=True, upload_to='storagemanagement/offer/deliverynote/', verbose_name='Lieferschein'),
        ),
        migrations.AddField(
            model_name='orderbasemodel',
            name='order_file',
            field=models.FileField(blank=True, help_text='Verschickte Bestellung', null=True, upload_to='storagemanagement/order/order', verbose_name='Bestellung'),
        ),
    ]
