# Generated by Django 4.2.7 on 2024-01-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0003_alter_storagemanagementstoragelistusersetting_supplieritem_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagemanagementstoragelistusersetting',
            name='price',
        ),
        migrations.RemoveField(
            model_name='storagemanagementstoragetableusersetting',
            name='price',
        ),
        migrations.AddField(
            model_name='storagemanagementstoragelistusersetting',
            name='value',
            field=models.BooleanField(default=True, help_text='Darstellung des Wertes', verbose_name='Wert'),
        ),
        migrations.AddField(
            model_name='storagemanagementstoragetableusersetting',
            name='value',
            field=models.BooleanField(default=True, help_text='Darstellung des Wertes', verbose_name='Wertes'),
        ),
    ]
