# Generated by Django 4.2.2 on 2023-11-10 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storagemanagement', '0003_alter_orderdata_options_offerbasemodel_offer_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdatabasemodel',
            name='authorized_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Zeitpunkt der Autorisierung.', verbose_name='Zeitpunkt der Autorisierung.'),
        ),
        migrations.AddField(
            model_name='requestdatabasemodel',
            name='authorized_user_id',
            field=models.ForeignKey(default=None, editable=False, help_text='Person der Autorisierung.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requestdata_authorized_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Autorisierer'),
        ),
        migrations.AlterField(
            model_name='offerdatabasemodel',
            name='companyitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerdata_companyitem', to='storagemanagement.companyitem', verbose_name='Firmenartikel'),
        ),
        migrations.AlterField(
            model_name='offerdatabasemodel',
            name='storageitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerdata_storageitem', to='storagemanagement.storageitem', verbose_name='Lagerartikel'),
        ),
        migrations.AlterField(
            model_name='orderdatabasemodel',
            name='companyitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderdata_companyitem', to='storagemanagement.companyitem', verbose_name='Firmenartikel'),
        ),
        migrations.AlterField(
            model_name='orderdatabasemodel',
            name='storageitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderdata_storageitem', to='storagemanagement.storageitem', verbose_name='Lagerartikel'),
        ),
    ]
