# Generated by Django 4.2.7 on 2024-01-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0004_remove_storagemanagementstoragelistusersetting_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagemanagementstoragelistusersetting',
            name='unload_date',
            field=models.BooleanField(default=True, help_text='Darstellung des Entnahme-Datum', verbose_name='Entnahme-Datum'),
        ),
        migrations.AddField(
            model_name='storagemanagementstoragelistusersetting',
            name='unload_time',
            field=models.BooleanField(default=True, help_text='Darstellung der Entnahme-Zeit', verbose_name='Entnahme-Zeit'),
        ),
        migrations.AddField(
            model_name='storagemanagementstoragelistusersetting',
            name='unload_user',
            field=models.BooleanField(default=True, help_text='Darstellung des Entnahme-Benutzer', verbose_name='Entnahme-Benutzer'),
        ),
        migrations.AddField(
            model_name='storagemanagementstoragetableusersetting',
            name='unload_date',
            field=models.BooleanField(default=True, help_text='Darstellung des Entnahme-Datum', verbose_name='Entnahme-Datum'),
        ),
        migrations.AddField(
            model_name='storagemanagementstoragetableusersetting',
            name='unload_time',
            field=models.BooleanField(default=True, help_text='Darstellung der Entnahme-Zeit', verbose_name='Entnahme-Zeit'),
        ),
        migrations.AddField(
            model_name='storagemanagementstoragetableusersetting',
            name='unload_user',
            field=models.BooleanField(default=True, help_text='Darstellung des Entnahme-Benutzer', verbose_name='Entnahme-Benutzer'),
        ),
    ]
