# Generated by Django 4.2.7 on 2024-01-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0005_storagemanagementstoragelistusersetting_unload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebasemodel',
            name='unload',
            field=models.BooleanField(default=False, help_text='Der Artikel wurde entnommen Ja/Nein.', verbose_name='Entnommen'),
        ),
    ]
