# Generated by Django 4.2.2 on 2023-11-11 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storagemanagement', '0005_alter_offerdatabasemodel_authorized_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdatabasemodel',
            name='recived_datetime',
            field=models.DateTimeField(blank=True, default=None, editable=False, help_text='Zeitpunkt des Erhalten der Bestellung.', null=True, verbose_name='Ankunft der Bestellung.'),
        ),
        migrations.AlterField(
            model_name='offerdatabasemodel',
            name='recived_user_id',
            field=models.ForeignKey(blank=True, default=None, editable=False, help_text='Person die die Bestellung erhalten hat.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offerdata_recived_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Person des Erhalten der Bestellung'),
        ),
        migrations.AlterField(
            model_name='offerdatabasemodel',
            name='sent_datetime',
            field=models.DateTimeField(blank=True, default=None, editable=False, help_text='Zeitpunkt der Bestellung.', null=True, verbose_name='Zeitpunkt der Bestellung.'),
        ),
        migrations.AlterField(
            model_name='offerdatabasemodel',
            name='sent_user_id',
            field=models.ForeignKey(blank=True, default=None, editable=False, help_text='Person die bestellt hat.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offerdata_sent_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Besteller'),
        ),
        migrations.AlterField(
            model_name='orderdatabasemodel',
            name='recived_datetime',
            field=models.DateTimeField(blank=True, default=None, editable=False, help_text='Zeitpunkt der Bestellung.', null=True, verbose_name='Zeitpunkt der Bestellung.'),
        ),
        migrations.AlterField(
            model_name='orderdatabasemodel',
            name='recived_user_id',
            field=models.ForeignKey(blank=True, default=None, editable=False, help_text='Person die die Bestellung erhalten hat.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderdata_recived_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Person des Erhalten der Bestellung'),
        ),
        migrations.AlterField(
            model_name='orderdatabasemodel',
            name='sent_datetime',
            field=models.DateTimeField(blank=True, default=None, editable=False, help_text='Zeitpunkt des Erhalten der Bestellung.', null=True, verbose_name='Ankunft der Bestellung.'),
        ),
        migrations.AlterField(
            model_name='orderdatabasemodel',
            name='sent_user_id',
            field=models.ForeignKey(blank=True, default=None, editable=False, help_text='Person die bestellt hat.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderdata_sent_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Besteller'),
        ),
    ]
