# Generated by Django 4.2.7 on 2024-01-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0007_storagemanagementbookinglistusersetting_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagemanagementbookinglistusersetting',
            name='storageitem_name',
            field=models.BooleanField(default=True, help_text='Darstellung des Lagerartikel', verbose_name='Lagerartikel'),
        ),
        migrations.AddField(
            model_name='storagemanagementbookinglistusersetting',
            name='storageitem_reference_number',
            field=models.BooleanField(default=True, help_text='Darstellung der Lagerartikelnummer', verbose_name='Lagerartikelnummer'),
        ),
        migrations.AddField(
            model_name='storagemanagementbookinglistusersetting',
            name='supplier_name',
            field=models.BooleanField(default=True, help_text='Darstellung des Lieferanten', verbose_name='Lieferant'),
        ),
        migrations.AddField(
            model_name='storagemanagementbookingtableusersetting',
            name='storageitem_name',
            field=models.BooleanField(default=True, help_text='Darstellung des Lagerartikel', verbose_name='Lagerartikel'),
        ),
        migrations.AddField(
            model_name='storagemanagementbookingtableusersetting',
            name='storageitem_reference_number',
            field=models.BooleanField(default=True, help_text='Darstellung der Lagerartikelnummer', verbose_name='Lagerartikelnummer'),
        ),
        migrations.AddField(
            model_name='storagemanagementbookingtableusersetting',
            name='supplier_name',
            field=models.BooleanField(default=True, help_text='Darstellung des Lieferanten', verbose_name='Lieferant'),
        ),
        migrations.AlterField(
            model_name='storagemanagementbookingtableusersetting',
            name='supplieritem_name',
            field=models.BooleanField(default=True, help_text='Darstellung des Artikels', verbose_name='Artikel'),
        ),
        migrations.AlterField(
            model_name='storagemanagementbookingtableusersetting',
            name='supplieritem_reference_number',
            field=models.BooleanField(default=True, help_text='Darstellung der Artikelreferenz', verbose_name='Artikelreferenz'),
        ),
    ]
