# Generated by Django 4.2.2 on 2023-11-11 17:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0007_alter_offerdatabasemodel_authorized_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbasemodel',
            name='notice',
            field=tinymce.models.HTMLField(blank=True, help_text='Nützliche Informationen zum Angebot.', null=True, verbose_name='Bemerkung'),
        ),
        migrations.AddField(
            model_name='offerdatabasemodel',
            name='notice',
            field=tinymce.models.HTMLField(blank=True, help_text='Nützliche Informationen für das Angebot.', null=True, verbose_name='Bemerkung'),
        ),
        migrations.AddField(
            model_name='requestdatabasemodel',
            name='notice',
            field=tinymce.models.HTMLField(blank=True, help_text='Nützliche Informationen zur Anfrage.', null=True, verbose_name='Bemerkung'),
        ),
    ]
