# Generated by Django 4.2.2 on 2023-11-11 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storagemanagement', '0008_offerbasemodel_notice_offerdatabasemodel_notice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdatabasemodel',
            name='done',
        ),
        migrations.RemoveField(
            model_name='offerdatabasemodel',
            name='recived',
        ),
        migrations.RemoveField(
            model_name='offerdatabasemodel',
            name='recived_datetime',
        ),
        migrations.RemoveField(
            model_name='offerdatabasemodel',
            name='recived_user_id',
        ),
        migrations.RemoveField(
            model_name='offerdatabasemodel',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='offerdatabasemodel',
            name='sent_datetime',
        ),
        migrations.RemoveField(
            model_name='offerdatabasemodel',
            name='sent_user_id',
        ),
        migrations.AddField(
            model_name='offerbasemodel',
            name='done',
            field=models.BooleanField(blank=True, default=False, help_text='Angebot wurde erledigt.', verbose_name='Erledigt'),
        ),
        migrations.AddField(
            model_name='offerbasemodel',
            name='recived',
            field=models.BooleanField(blank=True, default=False, help_text='Bestellung angekommen.', verbose_name='Erhalten.'),
        ),
        migrations.AddField(
            model_name='offerbasemodel',
            name='recived_datetime',
            field=models.DateTimeField(blank=True, default=None, editable=False, help_text='Zeitpunkt des Erhalten der Bestellung.', null=True, verbose_name='Ankunft der Bestellung.'),
        ),
        migrations.AddField(
            model_name='offerbasemodel',
            name='recived_user_id',
            field=models.ForeignKey(blank=True, default=None, editable=False, help_text='Person die die Bestellung erhalten hat.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_recived_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Person des Erhalten der Bestellung'),
        ),
        migrations.AddField(
            model_name='offerbasemodel',
            name='sent',
            field=models.BooleanField(blank=True, default=False, help_text='Bestellung wurde rausgeschickt.', verbose_name='Bestellt.'),
        ),
        migrations.AddField(
            model_name='offerbasemodel',
            name='sent_datetime',
            field=models.DateTimeField(blank=True, default=None, editable=False, help_text='Zeitpunkt der Bestellung.', null=True, verbose_name='Zeitpunkt der Bestellung.'),
        ),
        migrations.AddField(
            model_name='offerbasemodel',
            name='sent_user_id',
            field=models.ForeignKey(blank=True, default=None, editable=False, help_text='Person die bestellt hat.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_sent_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Besteller'),
        ),
    ]
