# Generated by Django 4.2.7 on 2024-01-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0008_storagemanagementbookinglistusersetting_storageitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagemanagementbookinglistusersetting',
            name='notice',
            field=models.BooleanField(default=True, help_text='Darstellung der Bemerkung', verbose_name='Bemerkung'),
        ),
        migrations.AddField(
            model_name='storagemanagementbookinglistusersetting',
            name='stock',
            field=models.BooleanField(default=True, help_text='Darstellung der Lagermenge', verbose_name='Lagermenge'),
        ),
        migrations.AddField(
            model_name='storagemanagementbookingtableusersetting',
            name='notice',
            field=models.BooleanField(default=True, help_text='Darstellung der Bemerkung', verbose_name='Bemerkung'),
        ),
        migrations.AddField(
            model_name='storagemanagementbookingtableusersetting',
            name='stock',
            field=models.BooleanField(default=True, help_text='Darstellung der Lagermenge', verbose_name='Lagermenge'),
        ),
    ]
