# Generated by Django 4.2.7 on 2024-01-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0009_storagemanagementbookinglistusersetting_notice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemanagementbookinglistusersetting',
            name='supplieritem_name',
            field=models.BooleanField(default=True, help_text='Darstellung des Artikels', verbose_name='Artikel'),
        ),
        migrations.AlterField(
            model_name='storagemanagementbookinglistusersetting',
            name='supplieritem_reference_number',
            field=models.BooleanField(default=True, help_text='Darstellung der Artikelreferenz', verbose_name='Artikelreferenz'),
        ),
    ]
