# Generated by Django 4.2.2 on 2023-11-11 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storagemanagement', '0009_remove_offerdatabasemodel_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerbasemodel',
            name='done',
        ),
        migrations.AddField(
            model_name='offerbasemodel',
            name='ordered',
            field=models.BooleanField(blank=True, default=False, help_text='Bestellung wurde aufgegeben.', verbose_name='Bestellung'),
        ),
        migrations.AddField(
            model_name='offerbasemodel',
            name='ordered_datetime',
            field=models.DateTimeField(blank=True, default=None, editable=False, help_text='Zeitpunkt der Erstellung der Bestellung.', null=True, verbose_name='Erstellung der Bestellung.'),
        ),
        migrations.AddField(
            model_name='offerbasemodel',
            name='ordered_user_id',
            field=models.ForeignKey(blank=True, default=None, editable=False, help_text='Person die die Bestellung erstellt hat.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_ordered_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Person der Erstellung der Bestellung'),
        ),
    ]
