# Generated by Django 4.2.2 on 2023-11-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0010_remove_offerbasemodel_done_offerbasemodel_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbasemodel',
            name='done',
            field=models.BooleanField(blank=True, default=False, help_text='Angebot wurde bearbeitet.', verbose_name='Bearbeitet'),
        ),
    ]
