# Generated by Django 4.2.2 on 2023-11-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0011_offerbasemodel_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'default_permissions': (), 'ordering': [], 'permissions': (('add_offer', 'Offer can view create'), ('authorize_true_offer', 'Offer can authorize false offer'), ('authorize_false_offer', 'Offer can authorize false offer'), ('change_offer', 'Offer can view change'), ('delete_offer', 'Offer can view delete'), ('detail_offer', 'Offer can view detail'), ('list_offer', 'Offer can view list'), ('recived_offer', 'Offer can recived offer'), ('sent_offer', 'Offer can sent offer'), ('order_true_offer', 'Offer can order true'), ('order_false_offer', 'Offer can order false'), ('table_offer', 'Offer can view table'), ('view_offer', 'Offer can view overview')), 'verbose_name': 'Angebot', 'verbose_name_plural': 'Angebote'},
        ),
        migrations.AlterField(
            model_name='orderdatabasemodel',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Menge'),
        ),
    ]
