# Generated by Django 4.2.7 on 2024-01-13 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storagemanagement', '0011_remove_supplieritembasemodel_supplieritem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageManagementRequestDataOverviewUserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Zeitpunkt der Erstellung.', verbose_name='Zeitpunkt der Erstellung')),
                ('update_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Zeitpunkt des letzten Updates.', verbose_name='Zeitpunkt des Updates')),
                ('api', models.CharField(default='storagemanagementAPI:requestdata_list', help_text='Url Adresse der API', max_length=200, verbose_name='API Url')),
                ('image', models.BooleanField(default=True, help_text='Darstellung des Bildes', verbose_name='Bild')),
                ('create_date', models.BooleanField(default=True, help_text='Darstellung des Erstellerdatums', verbose_name='Erstellerdatum')),
                ('create_time', models.BooleanField(default=True, help_text='Darstellung der Erstellerzeit', verbose_name='Erstellerzeit')),
                ('create_user', models.BooleanField(default=True, help_text='Darstellung des Erstellers', verbose_name='Ersteller')),
                ('update_date', models.BooleanField(default=True, help_text='Darstellung des Update-Datum', verbose_name='Update-Datum')),
                ('update_time', models.BooleanField(default=True, help_text='Darstellung der Update-Zeit', verbose_name='Update-Zeit')),
                ('update_user', models.BooleanField(default=True, help_text='Darstellung des Update-Benutzer', verbose_name='Update-Benutzer')),
                ('reference_number', models.BooleanField(default=True, help_text='Darstellung der Referenz Nummer', verbose_name='Referenznummer')),
                ('storageitem_name', models.BooleanField(default=True, help_text='Darstellung des Lagerartikel', verbose_name='Lagerartikel')),
                ('storageitem', models.BooleanField(default=True, help_text='Darstellung der Lagerartikelnummer', verbose_name='Lagerartikelnummer')),
                ('supplieritem_name', models.BooleanField(default=True, help_text='Darstellung des Lagerartikel', verbose_name='Lagerartikel')),
                ('supplieritem', models.BooleanField(default=True, help_text='Darstellung der Lagerartikelnummer', verbose_name='Lagerartikelnummer')),
                ('item_number', models.BooleanField(default=True, help_text='Darstellung der Artikelnummer', verbose_name='Artikelnummer')),
                ('supplier', models.BooleanField(default=True, help_text='Darstellung der Firma', verbose_name='Firma')),
                ('unit', models.BooleanField(default=True, help_text='Darstellung der Einheit', verbose_name='Einheit')),
                ('price', models.BooleanField(default=True, help_text='Darstellung des Preises', verbose_name='Preis')),
                ('url_unload', models.BooleanField(default=True, help_text='Darstellung des Links für eine Entnahme', verbose_name='Entnahme')),
                ('url_detail', models.BooleanField(default=True, help_text='Darstellung des Detail-Links', verbose_name='Detail-Link')),
                ('url_update', models.BooleanField(default=True, help_text='Darstellung des Update-links', verbose_name='Update-Link')),
                ('url_delete', models.BooleanField(default=True, help_text='Darstellung des Löschen-Links', verbose_name='Löschen-Link')),
                ('url_block', models.BooleanField(default=True, help_text='Darstellung aller Links in einem Block', verbose_name='Links')),
                ('create_user_id', models.ForeignKey(default=None, editable=False, help_text='Person der Erstellung.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss_create_user_id', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Ersteller')),
                ('update_user_id', models.ForeignKey(default=None, editable=False, help_text='Person des letzten Updates.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss_update_user_id', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storagemanagementrequestdataoverviewusersetting_user', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Einstellung Beziehungsmanagement Anfrage Übersicht',
                'verbose_name_plural': 'Einstellungen Beziehungsmanagement Anfragen Übersicht',
                'ordering': ['user'],
                'permissions': (('storagemanagement_requestdata_overview_setting', 'Storagemanagement Request Data overview can view Setting'),),
                'default_permissions': (),
            },
        ),
    ]
