# Generated by Django 4.2.7 on 2024-01-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0012_storagemanagementrequestdataoverviewusersetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagemanagementrequestdatalistusersetting',
            old_name='storageitem',
            new_name='storageitem_reference_number',
        ),
        migrations.RenameField(
            model_name='storagemanagementrequestdatalistusersetting',
            old_name='supplier',
            new_name='supplier_name',
        ),
        migrations.RenameField(
            model_name='storagemanagementrequestdatalistusersetting',
            old_name='item_number',
            new_name='supplieritem_item_number',
        ),
        migrations.RenameField(
            model_name='storagemanagementrequestdatalistusersetting',
            old_name='supplieritem',
            new_name='supplieritem_reference_number',
        ),
        migrations.RenameField(
            model_name='storagemanagementrequestdataoverviewusersetting',
            old_name='storageitem',
            new_name='storageitem_reference_number',
        ),
        migrations.RenameField(
            model_name='storagemanagementrequestdataoverviewusersetting',
            old_name='supplier',
            new_name='supplier_name',
        ),
        migrations.RenameField(
            model_name='storagemanagementrequestdataoverviewusersetting',
            old_name='item_number',
            new_name='supplieritem_item_number',
        ),
        migrations.RenameField(
            model_name='storagemanagementrequestdataoverviewusersetting',
            old_name='supplieritem',
            new_name='supplieritem_reference_number',
        ),
        migrations.RenameField(
            model_name='storagemanagementrequestdatatableusersetting',
            old_name='storageitem',
            new_name='storageitem_reference_number',
        ),
        migrations.RenameField(
            model_name='storagemanagementrequestdatatableusersetting',
            old_name='supplier',
            new_name='supplier_name',
        ),
        migrations.RenameField(
            model_name='storagemanagementrequestdatatableusersetting',
            old_name='item_number',
            new_name='supplieritem_item_number',
        ),
        migrations.RenameField(
            model_name='storagemanagementrequestdatatableusersetting',
            old_name='supplieritem',
            new_name='supplieritem_reference_number',
        ),
    ]
