# Generated by Django 4.2.2 on 2023-11-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0013_alter_offerdatabasemodel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdatabasemodel',
            name='done',
            field=models.BooleanField(blank=True, default=False, help_text='Artikel des Angebotes wurde bearbeitet.', null=True, verbose_name='Erledigt'),
        ),
    ]
