# Generated by Django 4.2.7 on 2024-01-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0013_rename_storageitem_storagemanagementrequestdatalistusersetting_storageitem_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdatabasemodel',
            name='supplieritem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestdata_supplieritem', to='storagemanagement.supplieritem', verbose_name='Item'),
        ),
    ]
