# Generated by Django 4.2.7 on 2024-01-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0014_alter_requestdatabasemodel_supplieritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagemanagementrequestdatalistusersetting',
            name='image',
        ),
        migrations.RemoveField(
            model_name='storagemanagementrequestdatalistusersetting',
            name='url_unload',
        ),
        migrations.RemoveField(
            model_name='storagemanagementrequestdataoverviewusersetting',
            name='image',
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatalistusersetting',
            name='amount',
            field=models.BooleanField(default=True, help_text='Darstellung der Menge', verbose_name='Menge'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatalistusersetting',
            name='authorized',
            field=models.BooleanField(default=True, help_text='Darstellung der Autorisierung', verbose_name='Autorisierung'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatalistusersetting',
            name='authorized_date',
            field=models.BooleanField(default=True, help_text='Darstellung des Autorisierungsdatums', verbose_name='Autorisierungsdatum'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatalistusersetting',
            name='authorized_time',
            field=models.BooleanField(default=True, help_text='Darstellung der Autorisierungszeit', verbose_name='Autorisierungszeit'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatalistusersetting',
            name='authorized_user',
            field=models.BooleanField(default=True, help_text='Darstellung des Autorisierers', verbose_name='Autorisierer'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatalistusersetting',
            name='done',
            field=models.BooleanField(default=True, help_text='Darstellung des Status', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatalistusersetting',
            name='notice',
            field=models.BooleanField(default=True, help_text='Darstellung der Bemerkung', verbose_name='Bemerkung'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatalistusersetting',
            name='value',
            field=models.BooleanField(default=True, help_text='Darstellung des Wertes', verbose_name='Wert'),
        ),
        migrations.AlterField(
            model_name='storagemanagementrequestdatalistusersetting',
            name='storageitem_reference_number',
            field=models.BooleanField(default=True, help_text='Darstellung der Lagerartikelreferenz', verbose_name='Lagerartikelreferenz'),
        ),
        migrations.AlterField(
            model_name='storagemanagementrequestdatalistusersetting',
            name='supplieritem_name',
            field=models.BooleanField(default=True, help_text='Darstellung des Artikels', verbose_name='Artikels'),
        ),
        migrations.AlterField(
            model_name='storagemanagementrequestdatalistusersetting',
            name='supplieritem_reference_number',
            field=models.BooleanField(default=True, help_text='Darstellung der Artikelreferenz', verbose_name='Artikelreferenz'),
        ),
    ]
