# Generated by Django 4.2.2 on 2023-11-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0014_offerdatabasemodel_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbasemodel',
            name='done',
            field=models.BooleanField(blank=True, default=False, help_text='Angebot wurde bearbeitet.', verbose_name='Bearbeitet'),
        ),
    ]
