# Generated by Django 4.2.7 on 2024-01-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0015_remove_storagemanagementrequestdatalistusersetting_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagemanagementrequestdatalistusersetting',
            old_name='authorized_user',
            new_name='authorized_username',
        ),
    ]
