# Generated by Django 4.2.2 on 2023-11-13 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storagemanagement', '0015_orderbasemodel_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdatabasemodel',
            name='recived',
        ),
        migrations.RemoveField(
            model_name='orderdatabasemodel',
            name='recived_datetime',
        ),
        migrations.RemoveField(
            model_name='orderdatabasemodel',
            name='recived_user_id',
        ),
        migrations.RemoveField(
            model_name='orderdatabasemodel',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='orderdatabasemodel',
            name='sent_datetime',
        ),
        migrations.RemoveField(
            model_name='orderdatabasemodel',
            name='sent_user_id',
        ),
        migrations.AddField(
            model_name='orderbasemodel',
            name='recived',
            field=models.BooleanField(blank=True, default=False, help_text='Bestellung angekommen.', verbose_name='Erhalten.'),
        ),
        migrations.AddField(
            model_name='orderbasemodel',
            name='recived_datetime',
            field=models.DateTimeField(blank=True, default=None, editable=False, help_text='Zeitpunkt der Bestellung.', null=True, verbose_name='Zeitpunkt der Bestellung.'),
        ),
        migrations.AddField(
            model_name='orderbasemodel',
            name='recived_user_id',
            field=models.ForeignKey(blank=True, default=None, editable=False, help_text='Person die die Bestellung erhalten hat.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_recived_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Person des Erhalten der Bestellung'),
        ),
        migrations.AddField(
            model_name='orderbasemodel',
            name='sent',
            field=models.BooleanField(blank=True, default=False, help_text='Bestellung wurde rausgeschickt.', verbose_name='Bestellt.'),
        ),
        migrations.AddField(
            model_name='orderbasemodel',
            name='sent_datetime',
            field=models.DateTimeField(blank=True, default=None, editable=False, help_text='Zeitpunkt des Erhalten der Bestellung.', null=True, verbose_name='Ankunft der Bestellung.'),
        ),
        migrations.AddField(
            model_name='orderbasemodel',
            name='sent_user_id',
            field=models.ForeignKey(blank=True, default=None, editable=False, help_text='Person die bestellt hat.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_sent_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Besteller'),
        ),
        migrations.AddField(
            model_name='orderdatabasemodel',
            name='booking',
            field=models.BooleanField(blank=True, default=None, help_text='Bestellung wurde gebucht.', null=True, verbose_name='Gebucht'),
        ),
        migrations.AddField(
            model_name='orderdatabasemodel',
            name='booking_datetime',
            field=models.DateTimeField(blank=True, default=None, editable=False, help_text='Zeitpunkt der Buchung.', null=True, verbose_name='Zeitpunkt der Buchung.'),
        ),
        migrations.AddField(
            model_name='orderdatabasemodel',
            name='booking_user_id',
            field=models.ForeignKey(blank=True, default=None, editable=False, help_text='Person der Buchung.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderdata_booking_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Bucher'),
        ),
    ]
