# Generated by Django 4.2.2 on 2023-11-13 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storagemanagement', '0016_remove_orderdatabasemodel_recived_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdata',
            options={'default_permissions': (), 'ordering': [], 'permissions': (('add_orderdata', 'OrderData can view create'), ('authorize_true_orderdata', 'OrderData can authorize true'), ('authorize_false_orderdata', 'OrderData can authorize false'), ('booking_true_orderdata', 'OrderData can booking true'), ('booking_false_orderdata', 'OrderData can booking false'), ('change_orderdata', 'OrderData can view change'), ('delete_orderdata', 'OrderData can view delete'), ('detail_orderdata', 'OrderData can view detail'), ('list_orderdata', 'OrderData can view list'), ('table_orderdata', 'OrderData can view table'), ('view_orderdata', 'OrderData can view overview')), 'verbose_name': 'Bestellung Artikel', 'verbose_name_plural': 'Bestellungen Artikel'},
        ),
        migrations.RemoveField(
            model_name='orderdatabasemodel',
            name='storageitem',
        ),
        migrations.AlterField(
            model_name='orderdatabasemodel',
            name='authorized_datetime',
            field=models.DateTimeField(blank=True, default=None, help_text='Zeitpunkt der Autorisierung.', null=True, verbose_name='Zeitpunkt der Autorisierung.'),
        ),
        migrations.AlterField(
            model_name='orderdatabasemodel',
            name='authorized_user_id',
            field=models.ForeignKey(blank=True, default=None, help_text='Person der Autorisierung.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderdata_authorized_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Autorisierer'),
        ),
        migrations.AlterField(
            model_name='orderdatabasemodel',
            name='booking_datetime',
            field=models.DateTimeField(blank=True, default=None, help_text='Zeitpunkt der Buchung.', null=True, verbose_name='Zeitpunkt der Buchung.'),
        ),
        migrations.AlterField(
            model_name='orderdatabasemodel',
            name='booking_user_id',
            field=models.ForeignKey(blank=True, default=None, help_text='Person der Buchung.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderdata_booking_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Bucher'),
        ),
    ]
