# Generated by Django 4.2.7 on 2024-01-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0017_storagemanagementrequestdatalistusersetting_url_authorize_false_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagemanagementrequestdatatableusersetting',
            name='image',
        ),
        migrations.RemoveField(
            model_name='storagemanagementrequestdatatableusersetting',
            name='url_unload',
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatalistusersetting',
            name='url_authorize',
            field=models.BooleanField(default=True, help_text='Darstellung des Autorisieren-Links', verbose_name='Autorisieren-Link'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatatableusersetting',
            name='amount',
            field=models.BooleanField(default=True, help_text='Darstellung der Menge', verbose_name='Menge'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatatableusersetting',
            name='authorized',
            field=models.BooleanField(default=True, help_text='Darstellung der Autorisierung', verbose_name='Autorisierung'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatatableusersetting',
            name='authorized_date',
            field=models.BooleanField(default=True, help_text='Darstellung des Autorisierungsdatums', verbose_name='Autorisierungsdatum'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatatableusersetting',
            name='authorized_time',
            field=models.BooleanField(default=True, help_text='Darstellung der Autorisierungszeit', verbose_name='Autorisierungszeit'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatatableusersetting',
            name='authorized_username',
            field=models.BooleanField(default=True, help_text='Darstellung des Autorisierers', verbose_name='Autorisierer'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatatableusersetting',
            name='done',
            field=models.BooleanField(default=True, help_text='Darstellung des Status', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatatableusersetting',
            name='notice',
            field=models.BooleanField(default=True, help_text='Darstellung der Bemerkung', verbose_name='Bemerkung'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatatableusersetting',
            name='url_authorize',
            field=models.BooleanField(default=True, help_text='Darstellung des Autorisieren-Links', verbose_name='Autorisieren-Link'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatatableusersetting',
            name='url_authorize_false',
            field=models.BooleanField(default=True, help_text='Darstellung des Ablehnen-Links', verbose_name='Ablehnen-Link'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatatableusersetting',
            name='url_authorize_true',
            field=models.BooleanField(default=True, help_text='Darstellung des Zustimmen-Links', verbose_name='Zustimmen-Link'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdatatableusersetting',
            name='value',
            field=models.BooleanField(default=True, help_text='Darstellung des Wertes', verbose_name='Wert'),
        ),
        migrations.AlterField(
            model_name='storagemanagementrequestdatalistusersetting',
            name='url_authorize_true',
            field=models.BooleanField(default=True, help_text='Darstellung des Zustimmen-Links', verbose_name='Zustimmen-Link'),
        ),
        migrations.AlterField(
            model_name='storagemanagementrequestdatatableusersetting',
            name='storageitem_reference_number',
            field=models.BooleanField(default=True, help_text='Darstellung der Lagerartikelreferenz', verbose_name='Lagerartikelreferenz'),
        ),
        migrations.AlterField(
            model_name='storagemanagementrequestdatatableusersetting',
            name='supplieritem_name',
            field=models.BooleanField(default=True, help_text='Darstellung des Artikels', verbose_name='Artikels'),
        ),
        migrations.AlterField(
            model_name='storagemanagementrequestdatatableusersetting',
            name='supplieritem_reference_number',
            field=models.BooleanField(default=True, help_text='Darstellung der Artikelreferenz', verbose_name='Artikelreferenz'),
        ),
    ]
