# Generated by Django 4.2.2 on 2023-11-13 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storagemanagement', '0017_alter_orderdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdatabasemodel',
            name='authorized_datetime',
            field=models.DateTimeField(blank=True, default=None, help_text='Zeitpunkt der Autorisierung.', null=True, verbose_name='Zeitpunkt der Autorisierung.'),
        ),
        migrations.AlterField(
            model_name='offerdatabasemodel',
            name='authorized_user_id',
            field=models.ForeignKey(blank=True, default=None, help_text='Person der Autorisierung.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offerdata_authorized_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Autorisierer'),
        ),
    ]
