# Generated by Django 4.2.7 on 2024-01-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagemanagement', '0018_remove_storagemanagementrequestdatatableusersetting_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagemanagementrequestdataoverviewusersetting',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='storagemanagementrequestdataoverviewusersetting',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='storagemanagementrequestdataoverviewusersetting',
            name='update_user',
        ),
        migrations.RemoveField(
            model_name='storagemanagementrequestdataoverviewusersetting',
            name='url_block',
        ),
        migrations.RemoveField(
            model_name='storagemanagementrequestdataoverviewusersetting',
            name='url_unload',
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdataoverviewusersetting',
            name='amount',
            field=models.BooleanField(default=True, help_text='Darstellung der Menge', verbose_name='Menge'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdataoverviewusersetting',
            name='notice',
            field=models.BooleanField(default=True, help_text='Darstellung der Bemerkung', verbose_name='Bemerkung'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdataoverviewusersetting',
            name='url_authorize_false',
            field=models.BooleanField(default=True, help_text='Darstellung des Ablehnen-Links', verbose_name='Ablehnen-Link'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdataoverviewusersetting',
            name='url_authorize_true',
            field=models.BooleanField(default=True, help_text='Darstellung des Zustimmen-Links', verbose_name='Zustimmen-Link'),
        ),
        migrations.AddField(
            model_name='storagemanagementrequestdataoverviewusersetting',
            name='value',
            field=models.BooleanField(default=True, help_text='Darstellung des Wertes', verbose_name='Wert'),
        ),
        migrations.AlterField(
            model_name='storagemanagementrequestdataoverviewusersetting',
            name='storageitem_reference_number',
            field=models.BooleanField(default=True, help_text='Darstellung der Lagerartikelreferenz', verbose_name='Lagerartikelreferenz'),
        ),
        migrations.AlterField(
            model_name='storagemanagementrequestdataoverviewusersetting',
            name='supplieritem_name',
            field=models.BooleanField(default=True, help_text='Darstellung des Artikels', verbose_name='Artikels'),
        ),
        migrations.AlterField(
            model_name='storagemanagementrequestdataoverviewusersetting',
            name='supplieritem_reference_number',
            field=models.BooleanField(default=True, help_text='Darstellung der Artikelreferenz', verbose_name='Artikelreferenz'),
        ),
    ]
