# Generated by Django 4.2.2 on 2023-11-18 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storagemanagement', '0019_orderdatabasemodel_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbasemodel',
            name='confirmation',
        ),
        migrations.AddField(
            model_name='orderbasemodel',
            name='notice',
            field=tinymce.models.HTMLField(blank=True, help_text='Nützliche Informationen zum Angebot.', null=True, verbose_name='Bemerkung'),
        ),
        migrations.AlterField(
            model_name='offerbasemodel',
            name='ordered_datetime',
            field=models.DateTimeField(blank=True, default=None, help_text='Zeitpunkt der Erstellung der Bestellung.', null=True, verbose_name='Erstellung der Bestellung.'),
        ),
        migrations.AlterField(
            model_name='offerbasemodel',
            name='ordered_user_id',
            field=models.ForeignKey(blank=True, default=None, help_text='Person die die Bestellung erstellt hat.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_ordered_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Person der Erstellung der Bestellung'),
        ),
        migrations.AlterField(
            model_name='offerbasemodel',
            name='recived_datetime',
            field=models.DateTimeField(blank=True, default=None, help_text='Zeitpunkt des Erhalten der Bestellung.', null=True, verbose_name='Ankunft der Bestellung.'),
        ),
        migrations.AlterField(
            model_name='offerbasemodel',
            name='recived_user_id',
            field=models.ForeignKey(blank=True, default=None, help_text='Person die die Bestellung erhalten hat.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_recived_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Person des Erhalten der Bestellung'),
        ),
        migrations.AlterField(
            model_name='offerbasemodel',
            name='sent_datetime',
            field=models.DateTimeField(blank=True, default=None, help_text='Zeitpunkt der Bestellung.', null=True, verbose_name='Zeitpunkt der Bestellung.'),
        ),
        migrations.AlterField(
            model_name='offerbasemodel',
            name='sent_user_id',
            field=models.ForeignKey(blank=True, default=None, help_text='Person die bestellt hat.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_sent_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Besteller'),
        ),
        migrations.AlterField(
            model_name='orderbasemodel',
            name='recived_datetime',
            field=models.DateTimeField(blank=True, default=None, help_text='Zeitpunkt der Bestellung.', null=True, verbose_name='Zeitpunkt der Bestellung.'),
        ),
        migrations.AlterField(
            model_name='orderbasemodel',
            name='recived_user_id',
            field=models.ForeignKey(blank=True, default=None, help_text='Person die die Bestellung erhalten hat.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_recived_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Person des Erhalten der Bestellung'),
        ),
        migrations.AlterField(
            model_name='orderbasemodel',
            name='sent_datetime',
            field=models.DateTimeField(blank=True, default=None, help_text='Zeitpunkt des Erhalten der Bestellung.', null=True, verbose_name='Ankunft der Bestellung.'),
        ),
        migrations.AlterField(
            model_name='orderbasemodel',
            name='sent_user_id',
            field=models.ForeignKey(blank=True, default=None, help_text='Person die bestellt hat.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_sent_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Besteller'),
        ),
    ]
