# Generated by Django 3.1.2 on 2020-10-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index1', models.CharField(max_length=200)),
                ('index2', models.CharField(max_length=200)),
                ('index3', models.CharField(max_length=200)),
            ],
        ),
    ]
