# Generated by Django 3.1.2 on 2020-10-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='index2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='index3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
