# Generated by Django 4.2.7 on 2023-12-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programm',
            options={'default_permissions': (), 'ordering': [], 'permissions': (('add_programm', 'Programm can view create'), ('change_programm', 'Programm can view change'), ('delete_programm', 'Programm can view delete'), ('detail_programm', 'Programm can view detail'), ('list_programm', 'Programm can view list'), ('programm_programm', 'Programm can view page'), ('table_programm', 'Programm can view table'), ('view_programm', 'Programm can view overview')), 'verbose_name': 'Programm', 'verbose_name_plural': 'Programme'},
        ),
        migrations.RemoveField(
            model_name='programmmanagementprogrammlistusersetting',
            name='html',
        ),
        migrations.AddField(
            model_name='programmmanagementprogrammlistusersetting',
            name='htmlfile_name',
            field=models.BooleanField(default=True, help_text='Darstellung des HTML Datei Namen', verbose_name='HTML Datei Name'),
        ),
        migrations.AddField(
            model_name='programmmanagementprogrammlistusersetting',
            name='htmlfile_url',
            field=models.BooleanField(default=True, help_text='Darstellung des Links der HTML Datei', verbose_name='Link HTML Datei'),
        ),
    ]
