# Generated by Django 4.2.7 on 2023-12-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmmanagement', '0002_alter_programm_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmmanagementprogrammtableusersetting',
            name='html',
        ),
        migrations.AddField(
            model_name='programmmanagementprogrammtableusersetting',
            name='htmlfile_name',
            field=models.BooleanField(default=True, help_text='Darstellung des HTML Datei Namen', verbose_name='HTML Datei Name'),
        ),
        migrations.AddField(
            model_name='programmmanagementprogrammtableusersetting',
            name='htmlfile_url',
            field=models.BooleanField(default=True, help_text='Darstellung des Links der HTML Datei', verbose_name='Link HTML Datei'),
        ),
    ]
