# Generated by Django 4.2.7 on 2023-12-17 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relationshipmanagement', '0002_relationshipmanagementusersetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipManagementCompanyListUserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Zeitpunkt der Erstellung.', verbose_name='Zeitpunkt der Erstellung')),
                ('update_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Zeitpunkt des letzten Updates.', verbose_name='Zeitpunkt des Updates')),
                ('company_list_reference_number', models.BooleanField(default=True, help_text='Darstellung der Referenz Nummer', verbose_name='Referenznummer')),
                ('company_list_name', models.BooleanField(default=True, help_text='Darstellung des Firmennamen', verbose_name='Firmenname')),
                ('company_list_street', models.BooleanField(default=True, help_text='Darstellung der Straße', verbose_name='Straße')),
                ('company_list_house_number', models.BooleanField(default=True, help_text='Darstellung der Straßennummer', verbose_name='Straßennummer')),
                ('company_list_postcode', models.BooleanField(default=True, help_text='Darstellung der Postleitzahl', verbose_name='Postleitzahl')),
                ('company_list_city', models.BooleanField(default=True, help_text='Darstellung der Stadt', verbose_name='Stadt')),
                ('company_list_country', models.BooleanField(default=True, help_text='Darstellung des Landes', verbose_name='Land')),
                ('company_list_phone', models.BooleanField(default=True, help_text='Darstellung der Telefonnummer', verbose_name='phone')),
                ('company_list_email', models.BooleanField(default=True, help_text='Darstellung der email', verbose_name='E-Mail')),
                ('company_list_contact', models.BooleanField(default=True, help_text='Darstellung der Anzahl der Kontakte', verbose_name='Kontakte')),
                ('company_list_item', models.BooleanField(default=True, help_text='Darstellung der Artikel', verbose_name='Artikel')),
                ('company_list_create_date', models.BooleanField(default=True, help_text='Darstellung des Erstellerdatums', verbose_name='Erstellerdatum')),
                ('company_list_create_time', models.BooleanField(default=True, help_text='Darstellung der Erstellerzeit', verbose_name='Erstellerzeit')),
                ('company_list_create_user', models.BooleanField(default=True, help_text='Darstellung des Erstellers', verbose_name='Ersteller')),
                ('company_list_update_date', models.BooleanField(default=True, help_text='Darstellung des Update-Datum', verbose_name='Update-Datum')),
                ('company_list_update_time', models.BooleanField(default=True, help_text='Darstellung der Update-Zeit', verbose_name='Update-Zeit')),
                ('company_list_update_user', models.BooleanField(default=True, help_text='Darstellung des Update-Benutzer', verbose_name='Update-Benutzer')),
                ('company_list_notice', models.BooleanField(default=True, help_text='Darstellung der Bemerkung', verbose_name='Bemerkung')),
                ('company_list_url_detail', models.BooleanField(default=True, help_text='Darstellung des Detail-Links', verbose_name='Detail-Link')),
                ('company_list_url_update', models.BooleanField(default=True, help_text='Darstellung des Update-links', verbose_name='Update-Link')),
                ('company_list_url_delete', models.BooleanField(default=True, help_text='Darstellung des Löschen-Links', verbose_name='Löschen-Link')),
                ('create_user_id', models.ForeignKey(default=None, editable=False, help_text='Person der Erstellung.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss_create_user_id', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Ersteller')),
                ('update_user_id', models.ForeignKey(default=None, editable=False, help_text='Person des letzten Updates.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss_update_user_id', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relationshipmanagementcompanylistusersetting_user', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Einstellung Liste Firmen Beziehungsmanagement',
                'verbose_name_plural': 'Einstellungen Liste Firmen Beziehungsmanagement',
                'ordering': ['user'],
                'permissions': (('relationshipmanagement_company_list_setting', 'Relationshipmanagement Company List can view Setting'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RelationshipManagementCompanyTableUserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Zeitpunkt der Erstellung.', verbose_name='Zeitpunkt der Erstellung')),
                ('update_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Zeitpunkt des letzten Updates.', verbose_name='Zeitpunkt des Updates')),
                ('company_table_reference_number', models.BooleanField(default=True, help_text='Darstellung der Referenz Nummer', verbose_name='Referenznummer')),
                ('company_table_name', models.BooleanField(default=True, help_text='Darstellung des Firmennamen', verbose_name='Firmenname')),
                ('company_table_street', models.BooleanField(default=True, help_text='Darstellung der Straße', verbose_name='Straße')),
                ('company_table_house_number', models.BooleanField(default=True, help_text='Darstellung der Straßennummer', verbose_name='Straßennummer')),
                ('company_table_postcode', models.BooleanField(default=True, help_text='Darstellung der Postleitzahl', verbose_name='Postleitzahl')),
                ('company_table_city', models.BooleanField(default=True, help_text='Darstellung der Stadt', verbose_name='Stadt')),
                ('company_table_country', models.BooleanField(default=True, help_text='Darstellung des Landes', verbose_name='Land')),
                ('company_table_phone', models.BooleanField(default=True, help_text='Darstellung der Telefonnummer', verbose_name='phone')),
                ('company_table_email', models.BooleanField(default=True, help_text='Darstellung der email', verbose_name='E-Mail')),
                ('company_table_contact', models.BooleanField(default=True, help_text='Darstellung der Anzahl der Kontakte', verbose_name='Kontakte')),
                ('company_table_item', models.BooleanField(default=True, help_text='Darstellung der Artikel', verbose_name='Artikel')),
                ('company_table_create_date', models.BooleanField(default=True, help_text='Darstellung des Erstellerdatums', verbose_name='Erstellerdatum')),
                ('company_table_create_time', models.BooleanField(default=True, help_text='Darstellung der Erstellerzeit', verbose_name='Erstellerzeit')),
                ('company_table_create_user', models.BooleanField(default=True, help_text='Darstellung des Erstellers', verbose_name='Ersteller')),
                ('company_table_update_date', models.BooleanField(default=True, help_text='Darstellung des Update-Datum', verbose_name='Update-Datum')),
                ('company_table_update_time', models.BooleanField(default=True, help_text='Darstellung der Update-Zeit', verbose_name='Update-Zeit')),
                ('company_table_update_user', models.BooleanField(default=True, help_text='Darstellung des Update-Benutzer', verbose_name='Update-Benutzer')),
                ('company_table_notice', models.BooleanField(default=True, help_text='Darstellung der Bemerkung', verbose_name='Bemerkung')),
                ('company_table_url_detail', models.BooleanField(default=True, help_text='Darstellung des Detail-Links', verbose_name='Detail-Link')),
                ('company_table_url_update', models.BooleanField(default=True, help_text='Darstellung des Update-links', verbose_name='Update-Link')),
                ('company_table_url_delete', models.BooleanField(default=True, help_text='Darstellung des Löschen-Links', verbose_name='Löschen-Link')),
                ('create_user_id', models.ForeignKey(default=None, editable=False, help_text='Person der Erstellung.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss_create_user_id', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Ersteller')),
                ('update_user_id', models.ForeignKey(default=None, editable=False, help_text='Person des letzten Updates.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss_update_user_id', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relationshipmanagementcompanytableusersetting_user', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Einstellung Beziehungsmanagement Firmen Tabelle',
                'verbose_name_plural': 'Einstellungen Beziehungsmanagement Firmen Tabelle',
                'ordering': ['user'],
                'permissions': (('relationshipmanagement_company_table_setting', 'Relationshipmanagement Company Table can view Setting'),),
                'default_permissions': (),
            },
        ),
        migrations.DeleteModel(
            name='RelationshipManagementUserSetting',
        ),
    ]
