# Generated by Django 4.2.7 on 2023-12-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipmanagement', '0003_relationshipmanagementcompanylistusersetting_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationshipmanagementcompanylistusersetting',
            options={'default_permissions': (), 'ordering': ['user'], 'permissions': (('relationshipmanagement_company_list_setting', 'Relationshipmanagement Company List can view Setting'),), 'verbose_name': 'Einstellung Beziehungsmanagement Firmen Liste', 'verbose_name_plural': 'Einstellungen Beziehungsmanagement Firmen Liste'},
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_create_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_create_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_create_user',
            new_name='create_user',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_house_number',
            new_name='house_number',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_notice',
            new_name='notice',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_postcode',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_reference_number',
            new_name='reference_number',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_street',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_update_date',
            new_name='update_date',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_update_time',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_update_user',
            new_name='update_user',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_url_delete',
            new_name='url_delete',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_url_detail',
            new_name='url_detail',
        ),
        migrations.RenameField(
            model_name='relationshipmanagementcompanylistusersetting',
            old_name='company_list_url_update',
            new_name='url_update',
        ),
        migrations.AddField(
            model_name='relationshipmanagementcompanylistusersetting',
            name='api',
            field=models.CharField(default='relationshipmanagementAPI:company_list', help_text='Url Adresse der API', max_length=200, verbose_name='API Url'),
        ),
    ]
