# Generated by Django 4.2.7 on 2023-12-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipmanagement', '0006_relationshipmanagementcompanyitemtableusersetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshipmanagementcompanycontactlistusersetting',
            name='name',
            field=models.BooleanField(default=True, help_text='Darstellung des Name', verbose_name='Name [Nachname, Vorname]'),
        ),
        migrations.AddField(
            model_name='relationshipmanagementcompanycontacttableusersetting',
            name='name',
            field=models.BooleanField(default=True, help_text='Darstellung des Name', verbose_name='Name [Nachname, Vorname]'),
        ),
        migrations.AlterField(
            model_name='relationshipmanagementcompanyitemlistusersetting',
            name='name',
            field=models.BooleanField(default=True, help_text='Darstellung des Artikels', verbose_name='Artikel'),
        ),
        migrations.AlterField(
            model_name='relationshipmanagementcompanyitemtableusersetting',
            name='name',
            field=models.BooleanField(default=True, help_text='Darstellung des Artikels', verbose_name='Artikel'),
        ),
    ]
