# Generated by Django 4.2.7 on 2023-12-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipmanagement', '0007_relationshipmanagementcompanycontactlistusersetting_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshipmanagementcompanycontactlistusersetting',
            name='url_block',
            field=models.BooleanField(default=True, help_text='Darstellung aller Links in einem Block', verbose_name='Links'),
        ),
        migrations.AddField(
            model_name='relationshipmanagementcompanycontacttableusersetting',
            name='url_block',
            field=models.BooleanField(default=True, help_text='Darstellung aller Links in einem Block', verbose_name='Links'),
        ),
        migrations.AddField(
            model_name='relationshipmanagementcompanyitemlistusersetting',
            name='url_block',
            field=models.BooleanField(default=True, help_text='Darstellung aller Links in einem Block', verbose_name='Links'),
        ),
        migrations.AddField(
            model_name='relationshipmanagementcompanyitemtableusersetting',
            name='url_block',
            field=models.BooleanField(default=True, help_text='Darstellung aller Links in einem Block', verbose_name='Links'),
        ),
        migrations.AddField(
            model_name='relationshipmanagementcompanylistusersetting',
            name='url_block',
            field=models.BooleanField(default=True, help_text='Darstellung aller Links in einem Block', verbose_name='Links'),
        ),
        migrations.AddField(
            model_name='relationshipmanagementcompanytableusersetting',
            name='url_block',
            field=models.BooleanField(default=True, help_text='Darstellung aller Links in einem Block', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='relationshipmanagementcompanycontactlistusersetting',
            name='name',
            field=models.BooleanField(default=True, help_text='Darstellung des Namen [Nachname, Vorname]', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='relationshipmanagementcompanycontacttableusersetting',
            name='name',
            field=models.BooleanField(default=True, help_text='Darstellung des Namen [Nachname, Vorname]', verbose_name='Name'),
        ),
    ]
