# Generated by Django 4.2.7 on 2023-12-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipmanagement', '0008_relationshipmanagementcompanycontactlistusersetting_url_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshipmanagementcompanyitemlistusersetting',
            name='url_request_create',
            field=models.BooleanField(default=True, help_text='Darstellung des Links für eine Preisanfrage', verbose_name='Preisanfrage'),
        ),
        migrations.AddField(
            model_name='relationshipmanagementcompanyitemtableusersetting',
            name='url_request_create',
            field=models.BooleanField(default=True, help_text='Darstellung des Links für eine Preisanfrage', verbose_name='Preisanfrage'),
        ),
    ]
