# Generated by Django 4.2.7 on 2023-12-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipmanagement', '0009_relationshipmanagementcompanyitemlistusersetting_url_request_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybasemodel',
            name='supplier',
            field=models.BooleanField(default=False, help_text='Ist die Firma ein Lieferant', verbose_name='Lieferant'),
        ),
    ]
