# Generated by Django 4.2.7 on 2024-01-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipmanagement', '0010_companybasemodel_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshipmanagementcompanylistusersetting',
            name='supplier',
            field=models.BooleanField(default=True, help_text='Darstellung des Lieferanten', verbose_name='Lieferant'),
        ),
        migrations.AddField(
            model_name='relationshipmanagementcompanytableusersetting',
            name='supplier',
            field=models.BooleanField(default=True, help_text='Darstellung des Lieferanten', verbose_name='Lieferant'),
        ),
    ]
