# Generated by Django 4.2.7 on 2024-01-05 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipmanagement', '0011_relationshipmanagementcompanylistusersetting_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontactbasemodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companycontact_company', to='relationshipmanagement.company', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='companyitembasemodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyitem_company', to='relationshipmanagement.company', verbose_name='Firma'),
        ),
    ]
