# Generated by Django 4.2.7 on 2023-12-16 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationbarItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Reihenfolge')),
                ('link', models.CharField(default='#', max_length=200, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Navigationbar',
                'verbose_name_plural': 'Navigationbar',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Reihenfolge')),
                ('link', models.CharField(default='#', max_length=200, verbose_name='Link')),
                ('navigationbarItem', models.ForeignKey(help_text='Navigationbar Item in der das Menu Item angezeigt werden soll.', on_delete=django.db.models.deletion.CASCADE, related_name='menuItemNavigationbarItem', to='main.navigationbaritem', verbose_name='Menu Item')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Reihenfolge')),
                ('link', models.CharField(default='#', max_length=200, verbose_name='Link')),
                ('menuItem', models.ForeignKey(help_text='Menu Item in der der Link angezeigt werden soll.', on_delete=django.db.models.deletion.CASCADE, related_name='linkMenuItem', to='main.menuitem', verbose_name='Menu Item')),
            ],
        ),
    ]
